import { Card, Term } from './types';

// الفئة الأولى: كروت المهام والتحديات (QUEST/MISSION DECK)
export const MISSION_DECK: Card[] = [
  { id: 'm1', category: 'QUEST', titleEn: 'Idiom', titleAr: 'اصطلاح', content: "It's raining cats and dogs", descriptionEn: 'Focus on the impact of heavy rain.', descriptionAr: 'ركز على أثر المطر الغزير لا على الحيوانات.', color: '#3B82F6', examples: ["السماء تصب صباً (Dynamic)", "تمطر بغزارة كأفواه القرب (Communicative)"] },
  { id: 'm2', category: 'QUEST', titleEn: 'Religious', titleAr: 'ديني', content: "الجنة تحت أقدام الأمهات", descriptionEn: 'Honor mothers in a way that resonates with the target audience.', descriptionAr: 'كرم الأمهات بأسلوب يمس وجدان المتلقي.', color: '#3B82F6', examples: ["Paradise lies at the feet of mothers [cite: 17]", "Motherhood is a path to paradise [cite: 17]"] },
  { id: 'm3', category: 'QUEST', titleEn: 'Proverb', titleAr: 'مثل', content: "A penny saved is a penny earned", descriptionEn: 'Find an Arabic proverb about thriftiness.', descriptionAr: 'جد حكمة عربية تحث على الاقتصاد والادخار.', color: '#3B82F6', examples: ["القرش الأبيض ينفع في اليوم الأسود [cite: 222]", "التوفير هو عين الكسب [cite: 221]"] },
  { id: 'm4', category: 'QUEST', titleEn: 'Literary', titleAr: 'أدبي', content: "She smiled, a tiny gesture that was both an apology and a secret", descriptionEn: 'Capture the poetic feel and emotional depth.', descriptionAr: 'انقل الحس الشاعري والعمق العاطفي خلف الابتسامة.', color: '#3B82F6', examples: ["ارتسمت على شفتيها ابتسامة خافتة بمثابة اعتذار وسر [cite: 101, 111]"] },
  { id: 'm5', category: 'QUEST', titleEn: 'Cultural', titleAr: 'ثقافي', content: "Insha'Allah", descriptionEn: 'Context dictates if it means "hopefully" or a "polite delay".', descriptionAr: 'السياق يحدد ما إذا كانت تعني "الأمل" أم "التأجيل المهذب".', color: '#3B82F6', examples: ["Hopefully [cite: 73, 490]", "God willing [cite: 73]", "We'll see [cite: 490]"] },
  { id: 'm6', category: 'QUEST', titleEn: 'Idiom', titleAr: 'اصطلاح', content: "He’s an early bird and always gets the worm", descriptionEn: 'Focus on the reward of being early.', descriptionAr: 'ركز على مكافأة التكبير والاجتهاد.', color: '#3B82F6', examples: ["من بكّر فلح (Dynamic)", "من طلب العلا سهر الليالي (Equivalence)"] },
  { id: 'm7', category: 'QUEST', titleEn: 'Simile', titleAr: 'تشبيه', content: "She felt like a fish out of water at the new job", descriptionEn: 'Convey the feeling of discomfort and being out of place.', descriptionAr: 'انقل الإحساس بعدم الارتياح والوحدة في المكان الجديد.', color: '#3B82F6', examples: ["شعرت بأنها غريبة تماماً في عملها الجديد (Dynamic)", "أحست بضيق كسمكة فارقت الماء (Literal)"] },
  { id: 'm8', category: 'QUEST', titleEn: 'News Headline', titleAr: 'عنوان إخباري', content: "New Policy: a double-edged sword for the economy", descriptionEn: 'Balance the positive and negative implications.', descriptionAr: 'وازن بين الآثار الإيجابية والسلبية للسياسة.', color: '#3B82F6', examples: ["سياسة جديدة: سيف ذو حدين للاقتصاد [cite: 534, 539]", "سياسة بمزايا وعيوب للاقتصاد [cite: 535, 541]"] },
  { id: 'm9', category: 'QUEST', titleEn: 'Idiom', titleAr: 'اصطلاح', content: "He was on thin ice after missing the deadline", descriptionEn: 'Express the danger of the situation.', descriptionAr: 'عبر عن خطورة الموقف وحرج الموقف.', color: '#3B82F6', examples: ["بات في وضع حرج للغاية (Dynamic)", "كان يمشي على قشر بيض (Cultural Equivalence)"] },
  { id: 'm10', category: 'QUEST', titleEn: 'Direct Expression', titleAr: 'تعبير مباشر', content: "الماء سر الحياة", descriptionEn: 'A foundational truth about water.', descriptionAr: 'حقيقة أساسية عن أهمية الماء.', color: '#3B82F6', examples: ["Water is the essence of life [cite: 195]", "Water is the source of life"] },
  { id: 'm11', category: 'QUEST', titleEn: 'Proverb', titleAr: 'مثل عربي', content: "العين لا تعلو على الحاجب", descriptionEn: 'Maintain the status hierarchy concept.', descriptionAr: 'حافظ على مفهوم التدرج والمكانة.', color: '#3B82F6', examples: ["The eye does not rise above the brow", "One must know their place"] },
  { id: 'm12', category: 'QUEST', titleEn: 'Arabic Wisdom', titleAr: 'حكمة عربية', content: "في التأني السلامة وفي العجلة الندامة", descriptionEn: 'Slow and steady leads to safety.', descriptionAr: 'التريث يقود للأمان والسرعة للخطأ.', color: '#3B82F6', examples: ["Haste makes waste [cite: 234, 236]", "Slow and steady wins the race [cite: 238]"] },
  { id: 'm13', category: 'QUEST', titleEn: 'Shared Idiom', titleAr: 'اصطلاح مشترك', content: "ضرب عصفورين بحجر واحد", descriptionEn: 'Achieving two goals at once.', descriptionAr: 'تحقيق هدفين بضربة واحدة.', color: '#3B82F6', examples: ["Killing two birds with one stone [cite: 202, 240]"] },
  { id: 'm14', category: 'QUEST', titleEn: 'Regional Idiom', titleAr: 'اصطلاح إقليمي', content: "باتت الأوضاع في المنطقة على كف عفريت", descriptionEn: 'The situation is highly volatile and unstable.', descriptionAr: 'الأوضاع في غاية الخطورة وعدم الاستقرار.', color: '#3B82F6', examples: ["The situation in the region is highly volatile [cite: 256, 259]", "The situation is on a razor's edge"] },
  { id: 'm15', category: 'QUEST', titleEn: 'Arabic Saying', titleAr: 'قول عربي', content: "الكلام يجر الكلام", descriptionEn: 'One topic leads to another.', descriptionAr: 'الحديث يفتح آفاقاً لحديث آخر.', color: '#3B82F6', examples: ["One thing leads to another [cite: 204, 446]", "Words drag words [cite: 445]"] },
  { id: 'm16', category: 'QUEST', titleEn: 'English Idiom', titleAr: 'اصطلاح إنجليزي', content: "To break a leg", descriptionEn: 'Wishing good luck in a performance.', descriptionAr: 'تمني الحظ السعيد في أداء فني.', color: '#3B82F6', examples: ["بالتوفيق [cite: 482, 483]", "حظاً سعيداً"] },
  { id: 'm17', category: 'QUEST', titleEn: 'Metaphor', titleAr: 'استعارة', content: "The straw that broke the camel's back", descriptionEn: 'The final minor irritation that causes a collapse.', descriptionAr: 'المشكلة البسيطة الأخيرة التي تسببت في الانفجار.', color: '#3B82F6', examples: ["القشة التي قصمت ظهر البعير [cite: 483, 484]"] },
  { id: 'm18', category: 'QUEST', titleEn: 'Oxford Metaphor', titleAr: 'استعارة مشاعر', content: "It was a bittersweet victory", descriptionEn: 'A victory tinged with sadness.', descriptionAr: 'نصر يختلط فيه الفرح بالمرارة.', color: '#3B82F6', examples: ["كان نصراً حلواً ومرّاً في آن واحد [cite: 493]"] },
  { id: 'm19', category: 'QUEST', titleEn: 'Passive Voice', titleAr: 'المبني للمجهول', content: "The book was read by the student", descriptionEn: 'Decide whether to keep passive or shift to active.', descriptionAr: 'قرر ما إذا كنت ستحافظ على المجهول أم ستغيره للمعلوم.', color: '#3B82F6', examples: ["قرأ الطالب الكتاب [cite: 333, 515]", "قُرئ الكتاب من قبل الطالب"] },
  { id: 'm20', category: 'QUEST', titleEn: 'Metaphor', titleAr: 'استعارة', content: "To turn over a new leaf", descriptionEn: 'Making a fresh, better start.', descriptionAr: 'البدء من جديد بأسلوب أفضل.', color: '#3B82F6', examples: ["فتح صفحة جديدة", "بدء حياة جديدة"] }
];

// الفئة الثانية: كروت الأدوات والنظريات (THEORY/POWER DECK)
export const THEORY_DECK: Card[] = [
  { id: 't1', category: 'TOOL', titleEn: 'Formal Equivalence', titleAr: 'التكافؤ الشكلي', content: 'Word-for-word', descriptionEn: 'Focus on reproducing the source form and structure [cite: 43].', descriptionAr: 'التركيز على محاكاة شكل وبنية النص المصدر[cite: 43].', color: '#10B981' },
  { id: 't2', category: 'TOOL', titleEn: 'Dynamic Equivalence', titleAr: 'التكافؤ الديناميكي', content: 'Meaning-for-meaning', descriptionEn: 'Focus on achieving an equivalent effect on the reader [cite: 49].', descriptionAr: 'التركيز على تحقيق أثر معادِل لدى القارئ[cite: 49].', color: '#10B981' },
  { id: 't3', category: 'TOOL', titleEn: 'Skopos Theory', titleAr: 'نظرية الهدف', content: 'Purpose-driven', descriptionEn: 'The purpose (skopos) of the translation dictates the strategy [cite: 336].', descriptionAr: 'الغرض من الترجمة هو ما يحدد الاستراتيجية المتبعة[cite: 336].', color: '#10B981' },
  { id: 't4', category: 'TOOL', titleEn: 'Catford’s Shift', titleAr: 'نقلات كاتفورد', content: 'Grammar Reordering', descriptionEn: 'Necessary grammatical or lexical changes between languages [cite: 330].', descriptionAr: 'تغييرات قواعدية أو لفظية ضرورية بين اللغتين[cite: 330].', color: '#10B981' },
  { id: 't5', category: 'TOOL', titleEn: 'Intralingual', titleAr: 'الترجمة ضمن اللغة', content: 'Rewording', descriptionEn: 'Paraphrasing within the same language [cite: 323].', descriptionAr: 'إعادة الصياغة أو التفسير داخل اللغة الواحدة[cite: 323].', color: '#10B981' },
  { id: 't6', category: 'TOOL', titleEn: 'Intersemiotic', titleAr: 'الترجمة السيميائية', content: 'Non-verbal Signs', descriptionEn: 'Translating text into visual, musical, or cinematic signs [cite: 327].', descriptionAr: 'نقل النص إلى إشارات بصرية أو موسيقية أو سينمائية[cite: 327].', color: '#10B981' },
  { id: 't7', category: 'TOOL', titleEn: 'Domestication', titleAr: 'التوطين', content: 'Natural Style', descriptionEn: 'Making the text as natural and familiar as possible for the target reader [cite: 638].', descriptionAr: 'جعل النص طبيعياً ومألوفاً قدر الإمكان للقارئ الهدف[cite: 638].', color: '#10B981' },
  { id: 't8', category: 'TOOL', titleEn: 'Foreignization', titleAr: 'التغريب', content: 'Source Flavor', descriptionEn: 'Retaining foreign cultural elements to challenge the reader [cite: 643].', descriptionAr: 'الاحتفاظ بعناصر الثقافة الأجنبية لتحدي القارئ[cite: 643].', color: '#10B981' },
  { id: 't9', category: 'TOOL', titleEn: 'Cultural Mediator', titleAr: 'الوسيط الثقافي', content: 'Bridge Cultures', descriptionEn: 'Acting as a bridge to help readers understand foreign concepts [cite: 126, 932].', descriptionAr: 'العمل كجسر لمساعدة القراء على فهم المفاهيم الأجنبية[cite: 126, 932].', color: '#10B981' },
  { id: 't10', category: 'TOOL', titleEn: 'Free Translation', titleAr: 'الترجمة الحرة', content: 'Creative Freedom', descriptionEn: 'Focus on conveying overall meaning with creative freedom [cite: 945].', descriptionAr: 'التركيز على نقل المعنى العام مع حرية إبداعية عالية[cite: 945].', color: '#10B981' },
  { id: 't11', category: 'TOOL', titleEn: 'Interlingual', titleAr: 'الترجمة بين اللغات', content: 'Between Languages', descriptionEn: 'Translation between two different languages [cite: 325].', descriptionAr: 'الترجمة التقليدية بين لغتين مختلفتين[cite: 325].', color: '#10B981' },
  { id: 't12', category: 'TOOL', titleEn: 'Explicitation', titleAr: 'التوضيح الإضافي', content: 'Explicit Nuance', descriptionEn: 'Making implicit source information explicit in the target text [cite: 968].', descriptionAr: 'إظهار المعلومات الضمنية في المصدر بشكل صريح في الهدف[cite: 968].', color: '#10B981' },
  { id: 't13', category: 'TOOL', titleEn: 'Omission', titleAr: 'الحذف المتعمد', content: 'Intentional Removal', descriptionEn: 'Leaving out content for ethical or cultural reasons [cite: 964, 1097].', descriptionAr: 'حذف بعض المحتوى لأسباب أخلاقية أو ثقافية[cite: 964, 1097].', color: '#10B981' },
  { id: 't14', category: 'TOOL', titleEn: 'Verb Tense Shift', titleAr: 'تغيير الزمن', content: 'Tense Context', descriptionEn: 'Choosing the correct tense based on the target language context [cite: 473].', descriptionAr: 'اختيار الزمن المناسب بناءً على سياق اللغة الهدف[cite: 473].', color: '#10B981' },
  { id: 't15', category: 'TOOL', titleEn: 'Structural Shift', titleAr: 'التصحيح الهيكلي', content: 'Arabic Nominal Sentence', descriptionEn: 'Removing unnecessary auxiliary verbs (like "to be") in Arabic nominal sentences [cite: 359, 362].', descriptionAr: 'حذف الأفعال المساعدة غير الضرورية في الجمل الاسمية العربية[cite: 359, 362].', color: '#10B981' },
  { id: 't16', category: 'TOOL', titleEn: 'Transcreation', titleAr: 'الإبداع التسويقي', content: 'Emotional Impact', descriptionEn: 'Adapting creative messages while maintaining emotion and intent [cite: 960, 1092].', descriptionAr: 'تكييف الرسائل الإبداعية مع الحفاظ على العاطفة والقصد[cite: 960, 1092].', color: '#10B981' },
  { id: 't17', category: 'TOOL', titleEn: 'Subject Matter Knowledge', titleAr: 'الخبير بالموضوع', content: 'Thematic Accuracy', descriptionEn: 'Deep understanding of the subject (medical, legal) to avoid errors [cite: 838, 880].', descriptionAr: 'الفهم العميق للموضوع (طبي، قانوني) لتجنب الأخطاء[cite: 838, 880].', color: '#10B981' },
  { id: 't18', category: 'TOOL', titleEn: 'Loyalty to Author', titleAr: 'صوت المؤلف', content: 'Author’s Intent', descriptionEn: 'Faithfully reproducing the exact words and intentions of the author [cite: 620].', descriptionAr: 'إعادة إنتاج كلمات ونوايا المؤلف الأصلي بأمانة[cite: 620].', color: '#10B981' },
  { id: 't19', category: 'TOOL', titleEn: 'Loyalty to Reader', titleAr: 'الوفاء للقارئ', content: 'Reader’s Accessibility', descriptionEn: 'Ensuring the message is clear and effective for target readers [cite: 622].', descriptionAr: 'ضمان وضوح الرسالة وفعاليتها للقارئ الهدف[cite: 622].', color: '#10B981' },
  { id: 't20', category: 'TOOL', titleEn: 'Manipulation', titleAr: 'المناورة', content: 'Cultural Norms', descriptionEn: 'Altering text to serve a specific purpose or cultural norm [cite: 771, 958].', descriptionAr: 'تعديل النص لخدمة غرض محدد أو معيار ثقافي[cite: 771, 958].', color: '#10B981' }
];

// الفئة الثالثة: كروت الأكشن والمفاجآت (TWIST DECK)
export const TWIST_DECK: Card[] = [
  { id: 'w1', category: 'TWIST', titleEn: 'Semantic Loss', titleAr: 'فخ الخسارة', content: 'Inevitable Loss', descriptionEn: 'Loss occurs when features like Arabic dual forms are lost in English [cite: 69, 72].', descriptionAr: 'يحدث الفقدان عند ضياع سمات كالمثنى العربي في الإنجليزية[cite: 69, 72].', color: '#EF4444' },
  { id: 'w2', category: 'TWIST', titleEn: 'Communicative Gain', titleAr: 'كنز المكسب', content: 'Contextual Gain', descriptionEn: 'Gain happens when adding clarifications to enhance the text [cite: 76, 78].', descriptionAr: 'يحدث المكسب عند إضافة توضيحات لتعزيز النص[cite: 76, 78].', color: '#EF4444' },
  { id: 'w3', category: 'TWIST', titleEn: 'Two-Stage Method', titleAr: 'حنين بن إسحق', content: 'Draft & Redraft', descriptionEn: 'First a literal draft, then a redrafting for naturalness [cite: 830, 868].', descriptionAr: 'مسودة حرفية أولاً، ثم إعادة صياغة لتحقيق السلاسة[cite: 830, 868].', color: '#EF4444' },
  { id: 'w4', category: 'TWIST', titleEn: 'Untranslatability', titleAr: 'الجاحظ', content: 'Rhetoric Hurdle', descriptionEn: 'The belief that poetry and rhetoric are untranslatable [cite: 837, 877].', descriptionAr: 'الإيمان بأن الشعر والبلاغة يستحيل نقلهما[cite: 837, 877].', color: '#EF4444' },
  { id: 'w5', category: 'TWIST', titleEn: 'Sense-for-sense', titleAr: 'سانت جيروم', content: 'Meaning Priority', descriptionEn: 'Advocating for translating the sense rather than word-for-word [cite: 827, 858].', descriptionAr: 'الدفاع عن ترجمة المعنى بدلاً من الترجمة كلمة بكلمة[cite: 827, 858].', color: '#EF4444' },
  { id: 'w6', category: 'TWIST', titleEn: 'Acceptability', titleAr: 'نيومار', content: 'Social Well-reception', descriptionEn: 'Being well-received by the target audience and functioning as intended [cite: 652].', descriptionAr: 'مدى قبول الجمهور الهدف للنص وأدائه لوظيفته[cite: 652].', color: '#EF4444' },
  { id: 'w7', category: 'TWIST', titleEn: 'Cultural Challenge', titleAr: 'التحدي الثقافي', content: 'Religious Terms', descriptionEn: 'Handling terms like "Hajj" without losing their cultural weight [cite: 645].', descriptionAr: 'التعامل مع مصطلحات كـ "الحج" دون فقدان ثقلها الثقافي[cite: 645].', color: '#EF4444' },
  { id: 'w8', category: 'TWIST', titleEn: 'Order Shift', titleAr: 'تغيير الترتيب', content: 'Catford’s Structural Shift', descriptionEn: 'Using Catford’s shift to fix awkward sentence structures [cite: 330, 498].', descriptionAr: 'استخدام نقلة كاتفورد لإصلاح التراكيب الركيكة[cite: 330, 498].', color: '#EF4444' },
  { id: 'w9', category: 'TWIST', titleEn: 'Descriptive Analysis', titleAr: 'المحقق (DTS)', content: 'Norm Analysis', descriptionEn: 'Studying why certain translation choices were made in real history [cite: 340, 372].', descriptionAr: 'دراسة أسباب اتخاذ قرارات ترجمية معينة في التاريخ[cite: 340, 372].', color: '#EF4444' },
  { id: 'w10', category: 'TWIST', titleEn: 'Ethical Dilemma', titleAr: 'الغموض القانوني', content: 'Clarify vs Directly Translate', descriptionEn: 'Deciding whether to clarify a legal ambiguity or translate it as is [cite: 757, 759].', descriptionAr: 'تقرير توضيح الغموض القانوني أو ترجمته كما هو[cite: 757, 759].', color: '#EF4444' },
  { id: 'w11', category: 'TWIST', titleEn: 'Invisibility', titleAr: 'الاختفاء', content: 'Venuti’s Concept', descriptionEn: 'Producing translations that read as if they were originally in the target language [cite: 850, 935].', descriptionAr: 'إنتاج ترجمات توهم القارئ بأنها نص أصلي[cite: 850, 935].', color: '#EF4444' },
  { id: 'w12', category: 'TWIST', titleEn: 'Gender Issues', titleAr: 'تعدد الهويات', content: 'Gender Nuance', descriptionEn: 'Handling gendered language (he/she/they) during translation [cite: 733, 734].', descriptionAr: 'التعامل مع لغة النوع (هو/هي/هما) أثناء الترجمة[cite: 733, 734].', color: '#EF4444' },
  { id: 'w13', category: 'TWIST', titleEn: 'Truth vs Words', titleAr: 'السراب', content: 'Meaning Integrity', descriptionEn: 'Ensuring everything built wasn\'t just a mirage in the desert [cite: 131, 149].', descriptionAr: 'التأكد من أن المعنى المبني لم يكن مجرد سراب[cite: 131, 149].', color: '#EF4444' },
  { id: 'w14', category: 'TWIST', titleEn: 'Polysystem', titleAr: 'النظام الأدبي', content: 'Genre Introduction', descriptionEn: 'Strategies for introducing a new genre into a target culture [cite: 769, 770].', descriptionAr: 'استراتيجيات إدخال نوع أدبي جديد للثقافة الهدف[cite: 769, 770].', color: '#EF4444' },
  { id: 'w15', category: 'TWIST', titleEn: 'Book Spine', titleAr: 'بين طيات الكتاب', content: 'Anatomical Accuracy', descriptionEn: 'Choosing natural terms like "طيات الكتاب" instead of literal "back" [cite: 98, 115].', descriptionAr: 'اختيار مصطلحات طبيعية كـ "طيات الكتاب" بدل الظهر الحرفي[cite: 98, 115].', color: '#EF4444' },
  { id: 'w16', category: 'TWIST', titleEn: 'Dynamic Style', titleAr: 'الصمت الرهيب', content: 'Atmospheric Flow', descriptionEn: 'Creating a poetic and fluid translation of a calm scene [cite: 106, 110].', descriptionAr: 'خلق ترجمة شاعرية وسلسة لمشهد هادئ[cite: 106, 110].', color: '#EF4444' },
  { id: 'w17', category: 'TWIST', titleEn: 'Emotional Power', titleAr: 'السكين', content: 'Idiomatic Impact', descriptionEn: 'Using strong equivalents like "knife plunged into his back" for idioms [cite: 148, 158].', descriptionAr: 'استخدام مرادفات قوية للتعبيرات الاصطلاحية المؤثرة[cite: 148, 158].', color: '#EF4444' },
  { id: 'w18', category: 'TWIST', titleEn: 'Ideology', titleAr: 'الهوية السياسية', content: 'Political Narrative', descriptionEn: 'Deciding between "freedom fighters" or "terrorists" [cite: 660, 663].', descriptionAr: 'تقرير الاختيار بين "مقاتلي حرية" أو "إرهابيين"[cite: 660, 663].', color: '#EF4444' },
  { id: 'w19', category: 'TWIST', titleEn: 'Metaphorical Trap', titleAr: 'فخ الاستعارة', content: 'Contextual Utility', descriptionEn: 'Determining if a literal or dynamic meaning is required [cite: 222].', descriptionAr: 'تحديد ما إذا كان المطلوب معنى حرفياً أم ديناميكياً[cite: 222].', color: '#EF4444' },
  { id: 'w20', category: 'TWIST', titleEn: 'Social Responsibility', titleAr: 'المسؤولية الاجتماعية', content: 'Impact Awareness', descriptionEn: 'Softening shocking content to suit local social values [cite: 708, 714].', descriptionAr: 'تلطيف المحتوى الصادم ليناسب القيم الاجتماعية المحلية[cite: 708, 714].', color: '#EF4444' }
];

// مسرد المصطلحات (GLOSSARY)
export const GLOSSARY_TERMS: Term[] = [
  { id: 'g1', term: 'Omission', definition: 'The act of intentionally leaving out a word or phrase from the source text [cite: 964, 1009, 1097].', example: "Removing references to alcohol for a conservative audience[cite: 966, 1011]." },
  { id: 'g2', term: 'Domestication', definition: 'Making the text conform to the target language culture and erase foreignness [cite: 638, 921, 1180].', example: "Translating 'Thanksgiving' as 'عشاء العيد' in a localized Arabic context[cite: 924]." },
  { id: 'g3', term: 'Foreignization', definition: 'Retaining cultural flavor of the source text, challenging target conventions [cite: 643, 926, 1183].', example: "Keeping terms like 'Hajj' or 'Kimchi' and adding footnotes[cite: 645, 930, 1132]." },
  { id: 'g4', term: 'Calque', definition: 'A word or phrase borrowed from another language by literal translation.', example: "'Skyscraper' translated as 'ناطحة سحاب' in Arabic." },
  { id: 'g5', term: 'Adaptation', definition: 'Full cultural re-creation where significant changes are made to suit target culture [cite: 939, 976, 1020].', example: "Localizing a video game's jokes and plot points for a specific market[cite: 941, 1025]." },
  { id: 'g6', term: 'Modulation', definition: 'Changing the semantic perspective of the message.', example: "Translating 'It is not difficult' as 'إنه سهل'." },
  { id: 'g7', term: 'Transposition', definition: 'Replacing one word class with another without changing the meaning.', example: "Changing a noun into a verb: 'After his arrival' to 'بعد أن وصل'." },
  { id: 'g8', term: 'Borrowing', definition: 'Taking a word directly from the source language without translation.', example: "Using 'Internet' directly in Arabic." },
  { id: 'g9', term: 'Explicitation', definition: 'Adding information to make implicit source meanings explicit in the target text [cite: 968, 1012, 1162].', example: "Adding gender-specific pronouns (هو/هي) absent in English[cite: 969, 1013]." },
  { id: 'g10', term: 'Transcreation', definition: 'Creative adaptation for marketing to maintain intent and emotional impact [cite: 960, 1004, 1168].', example: "Rewriting a brand tagline for the Arab market[cite: 961, 1007, 1095]." }
];